"""add vehicle_number to Reservation

Revision ID: 8d7e5166afcc
Revises: 80186d350378
Create Date: 2025-07-23 22:06:36.788906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7e5166afcc'
down_revision = '80186d350378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('reservation') as batch_op:
    batch_op.add_column(
        sa.Column(
            'vehicle_number',
            sa.String(length=50),
            nullable=True,               # allow NULL on existing rows
            server_default=''            # optional: supply empty-string default
        )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('vehicle_number')

    # ### end Alembic commands ###
